export const CREATE_BOOKING_REQUEST ="CREATE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS ="CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAILURE ="CREATE_BOOKING_FAILURE";


export const GET_USERS_BOOKING_REQUEST ="GET_USERS_BOOKING_REQUEST";
export const GET_USERS_BOOKING_SUCCESS ="GET_USERS_BOOKING_SUCCESS";
export const GET_USERS_BOOKING_FAILURE ="GET_USERS_BOOKING_FAILURE";


export const UPDATE_BOOKING_STATUS_RQUEST ="UPDATE_BOOKING_STATUS_RQUEST";
export const UPDATE_BOOKING_STATUS_SUCCESS ="UPDATE_BOOKING_STATUS_SUCCESS";
export const UPDATE_BOOKING_STATUS_FAILURE ="UPDATE_BOOKING_STATUS_FAILURE";


export const FIND_ALBUM_BY_BOOKING_EVENTID_RQUEST ="FIND_ALBUM_BY_BOOKING_EVENTID_RQUEST";
export const FIND_ALBUM_BY_BOOKING_EVENTID_SUCCESS ="FIND_ALBUM_BY_BOOKING_EVENTID_SUCCESS";
export const FIND_ALBUM_BY_BOOKING_EVENTID_FAILURE ="FIND_ALBUM_BY_BOOKING_EVENTID_FAILURE";
